### ISSUE TITLE
Error setting up development environment

### ISSUE THREAD

**Issue by joseluisjb1990** [vfarcic/books-ms#12]
Hi, I'm following the steps in chapter 4  about setting up the development environment and after executing the command 

**sudo docker run -it --rm -v $PWD/client/components:/source/client/components -v $PWD/client/test:/source/client/test -v $PWD/src:/source/src -v $PWD/target:/source/target -p 8080:8080 --env TEST_TYPE=watch-front vfarcic/books-ms-tests**

I've found the following error:

> > > NPM is broken (again) so front-end tests are temporarily disabled.
> > > mongod --help for help and startup options
> > > Sun Sep 25 21:02:12.224 [initandlisten] MongoDB starting : pid=5 port=27017 dbpath=/data/db/ 64-bit host=02b296a732fc
> > > Sun Sep 25 21:02:12.233 [initandlisten] db version v2.4.10
> > > Sun Sep 25 21:02:12.234 [initandlisten] git version: nogitversion
> > > Sun Sep 25 21:02:12.235 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
> > > Sun Sep 25 21:02:12.235 [initandlisten] allocator: tcmalloc
> > > Sun Sep 25 21:02:12.235 [initandlisten] options: {}
> > > Sun Sep 25 21:02:12.405 [initandlisten] journal dir=/data/db/journal
> > > Sun Sep 25 21:02:12.407 [initandlisten] recover : no journal files present, no recovery needed
> > > Sun Sep 25 21:02:12.856 [initandlisten] preallocateIsFaster=true 8.62
> > > Sun Sep 25 21:02:13.105 [initandlisten] preallocateIsFaster=true 3.6
> > > Sun Sep 25 21:02:14.224 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
> > > Sun Sep 25 21:02:14.225 [FileAllocator] creating directory /data/db/_tmp
> > > Sun Sep 25 21:02:14.227 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0 secs
> > > Sun Sep 25 21:02:14.243 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
> > > Sun Sep 25 21:02:14.254 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.009 secs
> > > Sun Sep 25 21:02:14.257 [initandlisten] waiting for connections on port 27017
> > > Sun Sep 25 21:02:14.260 [websvr] admin web console waiting for connections on port 28017
> > > [info] Loading project definition from /source/project
> > > [info] Set current project to books-ms (in build file:/source/)
> > > java.lang.RuntimeException: No main class detected.
> > >     at scala.sys.package$.error(package.scala:27)
> > > [trace] Stack trace suppressed: run last compile:run for the full output.
> > > [error](compile:run) No main class detected.
> > > [error] Total time: 1 s, completed Sep 25, 2016 9:02:46 PM

Before that, when I execute the command **ll** after accesing vagrant the directory is not sincronized with the repository.

**Comment by vfarcic** [comment]
The error indicates that the source code directory (`$PWD/src`) does not have the Scala code. Can you send me the path of the current directory (`pwd`) and its content (`ll`)?

**Comment by joseluisjb1990** [comment]
Thanks for your response.

pwd: /home/vagrant

ll: total 48
drwxr-xr-x 8 vagrant vagrant 4096 Sep 25 20:24 ./
drwxr-xr-x 4 root    root    4096 Sep 25 02:25 ../
drwx------ 3 vagrant vagrant 4096 Sep 25 02:35 .ansible/
-rw------- 1 vagrant vagrant 1910 Sep 25 22:43 .bash_history
-rw-r--r-- 1 vagrant vagrant  220 Apr  9  2014 .bash_logout
-rw-r--r-- 1 vagrant vagrant 3637 Apr  9  2014 .bashrc
drwx------ 2 vagrant vagrant 4096 Sep 25 02:25 .cache/
drwxr-xr-x 4 root    root    4096 Sep 25 03:17 client/
-rw-rw-r-- 1 vagrant vagrant    0 Sep 25 02:33 .cloud-locale-test.skip
-rw-r--r-- 1 vagrant vagrant  675 Apr  9  2014 .profile
drwxr-xr-x 2 root    root    4096 Sep 25 03:17 src/
drwxr-xr-x 2 vagrant vagrant 4096 Sep 22 21:31 .ssh/
drwxr-xr-x 5 root    root    4096 Sep 25 03:18 target/

**Comment by vfarcic** [comment]
Can you list the contents of the src directory?

**Comment by joseluisjb1990** [comment]
total 8
drwxr-xr-x 2 root    root    4096 Sep 25 03:17 ./
drwxr-xr-x 8 vagrant vagrant 4096 Sep 25 20:24 ../

**Comment by vfarcic** [comment]
The problem is that the source code was not cloned. Are you running this through the commands explained in [The DevOps 2.0 Toolkit](https://leanpub.com/the-devops-2-toolkit) book or from some of my blog posts? If it's one of those, I can tell you which step you missed. If it's neither, the solution is to clone the code first.

``` bash
git clone https://github.com/vfarcic/books-ms.git

cd books-ms
```

Now you can repeat the Docker command.

**Comment by vfarcic** [comment]
Please let me know if you're still facing the problem. If you are, can you ping me on Skype (user: vfarcic) or HangOuts (user: viktor@farcic.com) so that we take a look at it together?

**Comment by joseluisjb1990** [comment]
Yes, I'm facing the same problem. Maybe I'm missing some step? I cloned the repo, run _vagrant up dev_ and then _vagrant ssh dev_. After that, I run the docker command. It's important to notice that the directories are not synchronised after the  _vagrant ssh dev_ command.

**Comment by dalssaso** [comment]
@joseluisjb1990 if you didn't get this working yet, I think you should update the Guest Additions Manually according to your VirtualBox Host Version!

I mean, these vagrant boxes often come with Old versions of the Guest Additions package. What you could do is something like.

> PS.: I'm assuming that you have the latest version of VirtualBox and you have `wget` installed.

``` bash
cd YOUR_VAGRANT_FOLDER
vagrant ssh dev
wget http://download.virtualbox.org/virtualbox/5.1.6/VBoxGuestAdditions_5.1.6.iso
sudo mount -o loop VBoxGuestAdditions_5.1.6.iso /mnt
cd /mnt
sudo bash VBoxLinuxAdditions.run --nox11
exit
```

It should ask if you want to replace the older version to the new one, please type `yes`

Then you should reload the vagrant machine using the `vagrant reload` command outside of the machine (I've experienced issues running just `reboot` inside the machine

**Comment by joseluisjb1990** [comment]
Nothing. I upgraded vagrant and virtualbox. I also tried @hdalssaso solution. Nothing.

I installed Vagrant 1.8.6, virtualbox 5.0.26 r108824 running on debian 8.

I don't know what to do.

**Comment by dalssaso** [comment]
Hey, I think I saw some kind of typo on your comment and your environment!

If i'm correct you're trying to run that `docker command` inside of `/home/vagrant` and the correct directory is `/vagrant` as described inside of the `Vagrantfile`

``` ruby
config.vm.synced_folder ".", "/vagrant"
```

Try run that again inside of the directory `/vagrant`

**Comment by vfarcic** [comment]
Csn you please ping me on Skype or HangOuts so that we look at the problem together?

**Comment by vfarcic** [comment]
@hdaldsaso is right. Please enter the /vagrant dir.

**Comment by joseluisjb1990** [comment]
That was right! My problem is solved now! Many thanks to both of you for
helping me. I'll try to not be that dumb while reading the rest of the book.

**Comment by vfarcic** [comment]
@joseluisjb1990 Don't be tough on yourself. If there's anyone to blame that's me. I should have explained it better in the book.

**Comment by AJVA2580** [comment]
Hello, 

First of all, thank you for putting this amazing book together.  I am new to containers and to the whole CI/CD system. 

I have been trying to search for a possible solution to my issue. I am running this on a MacOs

1- I have re-started a few time chapter 5 - Deployment pipeline steps and every time I received a different error. 

  ~/books-ms 
   11 target/scalar-2.10/
zsh: command not found: 11

  ~/books-ms 
 ↵ 127  ll target/scalar-2.10/
zsh: command not found: ll

What is exactly the command it is number 11 or 2 ll? 
please advise and thank you

**Comment by vfarcic** [comment]
It's `ll` (two times letter `l`). It's a command that lists files and directories. Are you running those commands from `bash`? If you are, replace it with `ls -l` (`ll` is alias of that command) and let me know what you've got.

**Comment by AJVA2580** [comment]
Hell0,

Thank you for your kindly response.  I will try to do it.
