### ISSUE TITLE
in vagrant the docker cmd must be run with sudo?

### ISSUE THREAD

**Issue by tobyforever** [vfarcic/books-ms#14]
when I do "vagrant ssh" I find I must "sudo docker pull" rather than "docker pull", seems that user "vagrant" should be added to user group "docker" in order to run docker commands without sudo. (I referenced this url:
http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo ). 

should it be done in  the provisioning scripts?

**Comment by vfarcic** [comment]
You're right. We should not run Docker commands as sudo. However, that VM is for dev purposes only so security is not a concern. You will see that all other VMs in the book (those simulating "production" environments) have the vagrant user inside the docker group.
