### ISSUE TITLE
Page 60  the console hanged indefinitely 

### ISSUE THREAD

**Issue by tobyforever** [vfarcic/books-ms#15]
I am doing example on Page 60, the console seems to hang indefinitely after during docker run process.
anything wrong?  the cmd and  console output is as follows:

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo docker run -it --rm -v $PWD/client/components:/source/client/components -v $PWD/client/test:/source/client/test -v $PWD/src:/source/src -v $PWD/target:/source/target -p 8080:8080 --env TEST_TYPE=watch-front vfarcic/books-ms-tests

> > > NPM is broken (again) so front-end tests are temporarily disabled.
> > > mongod --help for help and startup options
> > > Wed Oct 12 07:58:14.849 [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data/db/ 64-bit host=4750e8c64bb1
> > > Wed Oct 12 07:58:14.854 [initandlisten] db version v2.4.10
> > > Wed Oct 12 07:58:14.858 [initandlisten] git version: nogitversion
> > > Wed Oct 12 07:58:14.860 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
> > > Wed Oct 12 07:58:14.862 [initandlisten] allocator: tcmalloc
> > > Wed Oct 12 07:58:14.862 [initandlisten] options: {}
> > > Wed Oct 12 07:58:14.870 [initandlisten] journal dir=/data/db/journal
> > > Wed Oct 12 07:58:14.872 [initandlisten] recover : no journal files present, no recovery needed
> > > Wed Oct 12 07:58:14.977 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
> > > Wed Oct 12 07:58:14.978 [FileAllocator] creating directory /data/db/_tmp
> > > Wed Oct 12 07:58:14.982 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0.002 secs
> > > Wed Oct 12 07:58:14.994 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
> > > Wed Oct 12 07:58:14.997 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.001 secs
> > > Wed Oct 12 07:58:15.002 [initandlisten] waiting for connections on port 27017
> > > Wed Oct 12 07:58:15.005 [websvr] admin web console waiting for connections on port 28017
> > > [info] Loading project definition from /source/project
> > > [info] Set current project to books-ms (in build file:/source/)
> > > [info] Compiling 2 Scala sources to /source/target/scala-2.10/classes...
> > > [info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
> > > [info]   Compilation completed in 27.358 s
> > > [info] Running com.technologyconversations.api.Service
> > > 07:59:42.118 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Registering Scala Conversions.
> > > 07:59:42.128 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Deserializers for Scala Conversions registering
> > > 07:59:42.129 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Serializers for Scala Conversions registering
> > > 07:59:42.131 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up OptionSerializer
> > > 07:59:42.136 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaProductSerializer
> > > 07:59:42.137 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaCollectionSerializer
> > > 07:59:42.140 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaRegexSerializers
> > > 07:59:42.143 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Hooking up scala.util.matching.Regex serializer
> > > 07:59:42.145 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Reached base registration method on MongoConversionHelper.
> > > Wed Oct 12 07:59:43.270 [initandlisten] connection accepted from 127.0.0.1:45127 #1 (1 connection now open)
> > > [INFO] [10/12/2016 07:59:43.780] [routingSystem-akka.actor.default-dispatcher-3] [akka://routingSystem/user/IO-HTTP/listener-0] Bound to /0.0.0.0:8080
> > > [INFO] [10/12/2016 07:59:43.793] [routingSystem-akka.actor.default-dispatcher-2] [akka://routingSystem/deadLetters] Message [akka.io.Tcp$Bound] from Actor[akka://routingSystem/user/IO-HTTP/listener-0#-1531932518] to Actor[akka://routingSystem/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by vfarcic** [comment]
At this point in time, the container would wait for the changes to the front-end code. However, FE tests were disabled due to problems with NPM. You can see the output as it should be (if NPM would be working) in the book. Please stop it with CTRL+c and proceed with the rest of the chapter.

**Comment by rodhall85** [comment]
I'm facing this issue as well. How can we make NPM 'unbroken' or is it just that it's borked in the current version of the image? Could I perhaps manually install it from within?

**Comment by vfarcic** [comment]
To enable the NPM tests, just uncomment the following:
https://github.com/vfarcic/books-ms/blob/master/run_tests.sh#L15
https://github.com/vfarcic/books-ms/blob/master/run_tests.sh#L25
... and rebuild the container.

Please let me know if it worked out and if it did, we can uncomment it permanently.

**Comment by xnandersson** [comment]
I'm getting this error:

vagrant@vagrant-ubuntu-trusty-64:~$ sudo ./test.sh 

> > > NPM is broken (again) so front-end tests are temporarily disabled.
> > > mongod --help for help and startup options
> > > Mon Nov 14 18:23:39.297 [initandlisten] MongoDB starting : pid=5 port=27017 dbpath=/data/db/ 64-bit host=7bc4655f7334
> > > Mon Nov 14 18:23:39.298 [initandlisten] db version v2.4.10
> > > Mon Nov 14 18:23:39.298 [initandlisten] git version: nogitversion
> > > Mon Nov 14 18:23:39.299 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
> > > Mon Nov 14 18:23:39.300 [initandlisten] allocator: tcmalloc
> > > Mon Nov 14 18:23:39.300 [initandlisten] options: {}
> > > Mon Nov 14 18:23:39.301 [initandlisten] journal dir=/data/db/journal
> > > Mon Nov 14 18:23:39.301 [initandlisten] recover : no journal files present, no recovery needed
> > > Mon Nov 14 18:23:39.333 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
> > > Mon Nov 14 18:23:39.334 [FileAllocator] creating directory /data/db/_tmp
> > > Mon Nov 14 18:23:39.336 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0 secs
> > > Mon Nov 14 18:23:39.345 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
> > > Mon Nov 14 18:23:39.347 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.001 secs
> > > Mon Nov 14 18:23:39.348 [initandlisten] waiting for connections on port 27017
> > > Mon Nov 14 18:23:39.350 [websvr] admin web console waiting for connections on port 28017
> > > [info] Loading project definition from /source/project
> > > [info] Set current project to books-ms (in build file:/source/)
> > > [info] Updating {file:/source/}source...
> > > [info] Resolving org.fusesource.jansi#jansi;1.4 ...
> > > [info] Done updating.
> > > java.lang.RuntimeException: No main class detected.
> > >     at scala.sys.package$.error(package.scala:27)
> > > [trace] Stack trace suppressed: run last compile:run for the full output.
> > > [error](compile:run) No main class detected.
> > > [error] Total time: 6 s, completed Nov 14, 2016 6:24:09 PM
> > > ^CMon Nov 14 18:29:55.185 [signalProcessingThread] got signal 2 (Interrupt), will terminate after current cmd ends
> > > ^Cvagrant@vagrant-ubuntu-trusty-64:~$

Command is:

sudo docker run -it --rm \
  -v $PWD/client/components:/source/client/components \
  -v $PWD/client/test:/source/client/test \
  -v $PWD/src:/source/src \
  -v $PWD/target:/source/target \
  -p 8080:8080 \
  --env TEST_TYPE=watch-front \
  vfarcic/books-ms-tests

...my versions:

vagrant@vagrant-ubuntu-trusty-64:~$ docker --version
Docker version 1.12.3, build 6b644ec
vagrant@vagrant-ubuntu-trusty-64:~$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
vagrant@vagrant-ubuntu-trusty-64:~$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
vagrant@vagrant-ubuntu-trusty-64:~$ docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
vfarcic/books-ms-tests   latest              967207047a03        3 months ago        2.244 GB

**Comment by xnandersson** [comment]
Oh, and thanks for what looks like a great book. I am just getting started here and are really looking forward to it :-)

**Comment by vfarcic** [comment]
The error indicates that the source code is not available.

Vagrant mounts the current local directory inside VM as `/vagrant`. The commands before the one that fail should placed you inside `/vagrant`. Can you confirm that you are inside the directory and that the source code is there? Please execute the commands that follow and send me the output.

``` sh
vagrant ssh dev

cd /vagrant

pwd

ll
```

**Comment by xnandersson** [comment]
Oh. Sorry. I did that and now it works. I saw the reference to enter /vagrant top on page 62, and the code snippet was on page 64. Thanks for your help!

**Comment by vfarcic** [comment]
I'm glad it worked out.

Closing the ticket.
