### ISSUE TITLE
book-ms P66  Issue for java.lang.RuntimeException: No main class detected.

### ISSUE THREAD

**Issue by JerryChenZeyun** [vfarcic/books-ms#19]
After installed the books_ms_dev VM and have docker engine up and running, I follow the instruction on P66 to type in the following command:

-------------------Command---------------------
sudo docker run -it --rm -v $PWD/client/components:/source/client/components -v $PWD/client/test:/source/client/test -v $PWD/src:/source/src -v $PWD/target:/source/target -p 8080:8080 --env TEST_TYPE=watch-front vfarcic/books-ms-tests
--------------------------------------------------

Then ISSUE of **'java.lang.RuntimeException: No main class detected. at scala.sys.package$.error(package.scala:27)'** occurs. 

Moreover, I cann't access the http://10.100.199.200:8080/components/tc-books/demo/index.html through my local MAC browser.

This issue has blocked me a whole day but still can't get through. Can anyone help on this issue? 
Thanks a lot!

**Comment by vfarcic** [comment]
The most likely cause of the problem is that you are not inside the directory with the source code so there is nothing to build. Can you double check that you are inside the "books-ms" dir?

```sh
pwd
```

**Comment by JerryChenZeyun** [comment]
Hi Viktor,

You are right. The main reason for this mistake is that it's a little
confusing for me to switch the folders between "books-ms" and
"books-ms-master". Sorry for making such careless mistake and thank you for
the explanation!

Best Regards!

Zeyun Chen
Enjoy Life Everyday :)
Mobile Phone: +86 186 1142 6368

2016-11-22 13:28 GMT+08:00 Viktor Farcic notifications@github.com:

**Comment by vfarcic** [comment]
I'm glad it worked out.

I'll close the ticket. Feel free to reopen it if you feel there's still something that I can help with.
