### ISSUE TITLE
How to work with multiple boxes.

### ISSUE THREAD

**Issue by bweston92** [vfarcic/books-ms#2]
I'm reading your book. how-ever I have a few questions. Mainly how can I have more then 1 box?

For example:
- Box 1 - Ubuntu - with Jenkins etc on.
- Box 2 - CoreOS - which the containers are deployed on to using fleet.

**Comment by vfarcic** [comment]
That depends how would you create boxes. Can you tell me whether you're using Vagrant, AWS, VMWare, ...? For example, in the Vagrantfile used throughout the book, one of the VM definitions is:

  config.vm.define "cd" do |d|
    d.vm.box = "ubuntu/trusty64"
    d.vm.hostname = "cd"
    d.vm.network "private_network", ip: "10.100.198.200"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/cd.yml -c local"
    d.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end

The part that defines the OS is:
 d.vm.box = "ubuntu/trusty64"

It can be any of the available Vagrant boxes and different types can be combined inside a single Vagrantfile.

Can you tell me more about the goals you're trying to accomplish? Feel free to contact me on HangOuts or Skype.

**Comment by vfarcic** [comment]
I'll close this issue. Please reopen it if you still have problems.

**Comment by bweston92** [comment]
I actually don't have AWS, but for deploying a VM I use libvirt which is a bit like Vagrant except a manual process (no Vagrantfile just bash scripts).

Would you suggest using Vagrant on a server I thought was development only?

**Comment by vfarcic** [comment]
I don't suggest using Vagrant for production even though there are many cases of people doing it. No matter which way you choose to create VMs, the major choice you should make is whether to provision them after they are created (e.g. Ansible) or to "bake" images with everything inside (e.g. Packer).

**Comment by bweston92** [comment]
Not heard of Packer! Will give it a look, thanks for your help!
