### ISSUE TITLE
Devlopment Environment Setup (macOS Sierra)

### ISSUE THREAD

**Issue by peatey** [vfarcic/books-ms#21]
Hi Guys,

not sure if anyone else has come across this so I thought it was worth raising. When running the initial Vagrant 

`vagrant up dev`

from the chapter titled "Setting Up the Development Environment with Vagrant and Docker" I ran into issues accessing the HashiCorp source. Turns out to be a bug with Vagrant 1.8.7 and you have to run

`sudo rm /opt/vagrant/embedded/bin/curl`

apparently an issue which will be patched in  1.8.8. Details are on the Vagrant issue list as #354 

I will close this when 1.8.8 is released and tested.

**Comment by peatey** [comment]
1.9.0 is out

changes are here: https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md

no mention of this issue being fixed. Will need to test

**Comment by vfarcic** [comment]
Thank you for helping on this issue.

Please let me know how it went.

**Comment by vfarcic** [comment]
Did you manage to test it? I haven't had the same problem on my mac so I can confirm whether the fix works or it doesn't.

**Comment by edwize** [comment]
I'm running Vagrant 1.9.1 on my MAC El Capitan and did not come across that error.
It must be fixed.

**Comment by vfarcic** [comment]
Closing the ticket. Please reopen if you're still experiencing the problem.

**Comment by peatey** [comment]
thanks guys sorry for not testing christmas etc etc
