### ISSUE TITLE
Unable To Run Tests In Chapter 4

### ISSUE THREAD

**Issue by tompurl** [vfarcic/books-ms#24]
I'm having some issues running the automated tests in Chapter 4. Here's what I got when I tried running the "raw" docker command:

    >>> NPM is broken (again) so front-end tests are temporarily disabled.
    mongod --help for help and startup options
    Wed Dec 28 15:32:11.283 [initandlisten] MongoDB starting : pid=5 port=27017 dbpath=/data/db/ 64-bit host=cb17dc8f882f
    Wed Dec 28 15:32:11.287 [initandlisten] db version v2.4.10
    Wed Dec 28 15:32:11.287 [initandlisten] git version: nogitversion
    Wed Dec 28 15:32:11.287 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
    Wed Dec 28 15:32:11.287 [initandlisten] allocator: tcmalloc
    Wed Dec 28 15:32:11.287 [initandlisten] options: {}
    Wed Dec 28 15:32:11.343 [initandlisten] journal dir=/data/db/journal
    Wed Dec 28 15:32:11.344 [initandlisten] recover : no journal files present, no recovery needed
    Wed Dec 28 15:32:11.490 [initandlisten] preallocateIsFaster=true 2.46
    Wed Dec 28 15:32:11.531 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
    Wed Dec 28 15:32:11.532 [FileAllocator] creating directory /data/db/_tmp
    Wed Dec 28 15:32:11.533 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0 secs
    Wed Dec 28 15:32:11.544 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
    Wed Dec 28 15:32:11.545 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0 secs
    Wed Dec 28 15:32:11.551 [initandlisten] waiting for connections on port 27017
    Wed Dec 28 15:32:11.553 [websvr] admin web console waiting for connections on port 28017
    [info] Loading project definition from /source/project
    [info] Set current project to books-ms (in build file:/source/)
    [info] Updating {file:/source/}source...
    [info] Resolving org.fusesource.jansi#jansi;1.4 ...
    [info] Done updating.
    java.lang.RuntimeException: No main class detected.
            at scala.sys.package$.error(package.scala:27)
    [trace] Stack trace suppressed: run last compile:run for the full output.
    [error] (compile:run) No main class detected.
    [error] Total time: 7 s, completed Dec 28, 2016 3:32:45 PM

I then tried running the "fsTestsLocal" command with `docker-compose`. Here's the output:

    WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
    >>> NPM is broken (again) so front-end tests are temporarily disabled.
    mongod --help for help and startup options
    Wed Dec 28 15:43:48.185 [initandlisten] MongoDB starting : pid=5 port=27017 dbpath=/data/db/ 64-bit host=f9caf2d7c946
    Wed Dec 28 15:43:48.198 [initandlisten] db version v2.4.10
    Wed Dec 28 15:43:48.198 [initandlisten] git version: nogitversion
    Wed Dec 28 15:43:48.198 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55Wed Dec 28 15:43:48.199 [initandlisten] allocator: tcmalloc
    Wed Dec 28 15:43:48.199 [initandlisten] options: {}
    Wed Dec 28 15:43:48.203 [initandlisten] journal dir=/data/db/journal
    Wed Dec 28 15:43:48.203 [initandlisten] recover : no journal files present, no recovery needed
    Wed Dec 28 15:43:48.315 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
    Wed Dec 28 15:43:48.316 [FileAllocator] creating directory /data/db/_tmp
    Wed Dec 28 15:43:48.317 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0.001 secs
    Wed Dec 28 15:43:48.329 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
    Wed Dec 28 15:43:48.363 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.032 secs
    Wed Dec 28 15:43:48.373 [initandlisten] waiting for connections on port 27017
    Wed Dec 28 15:43:48.373 [websvr] admin web console waiting for connections on port 28017
    [info] Loading project definition from /source/project
    [info] Set current project to books-ms (in build file:/source/)
    [info] Updating {file:/source/}source...
    [info] Resolving org.fusesource.jansi#jansi;1.4 ...
    [info] Done updating.
    [info] Compiling 2 Scala sources to /source/target/scala-2.10/classes...
    [info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
    [info]   Compilation completed in 23.54 s
    [info] Running com.technologyconversations.api.Service 
    15:45:23.558 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Registering Scala Conversions.
    15:45:23.579 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Deserializers for Scala Conversions registering
    15:45:23.581 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Serializers for Scala Conversions registering
    15:45:23.582 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up OptionSerializer
    15:45:23.584 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaProductSerializer
    15:45:23.595 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaCollectionSerializer
    15:45:23.596 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaRegexSerializers
    15:45:23.596 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Hooking up scala.util.matching.Regex serializer
    15:45:23.597 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Reached base registration method on Mongo
    ConversionHelper.
    [INFO] [12/28/2016 15:45:24.812] [routingSystem-akka.actor.default-dispatcher-4] [akka://routingSystem/user/IO-HTTP/listener-0] Bound to /0.0.0.0:808
    0
    [INFO] [12/28/2016 15:45:24.826] [routingSystem-akka.actor.default-dispatcher-2] [akka://routingSystem/deadLetters] Message [akka.io.Tcp$Bound] from 
    Actor[akka://routingSystem/user/IO-HTTP/listener-0#588689481] to Actor[akka://routingSystem/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
    Wed Dec 28 15:45:24.845 [initandlisten] connection accepted from 127.0.0.1:54525 #1 (1 connection now open)

No outright errors this time but I don't see the tests being executed. Also, I'm not able to connect to http://10.100.199.200:8080/components/tc-books/demo/index.html. I'm also not even able to ping the port from the machine that hosts Vagrant:

    $ nc -vzz 10.100.199.200 8080
    10.100.199.200: inverse host lookup failed: Unknown host
    (UNKNOWN) [10.100.199.200] 8080 (http-alt) : Connection refused

This is confusing because it looks like the VM is listening on this port:

    $ vagrant ssh dev
    Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-101-generic x86_64)

     * Documentation:  https://help.ubuntu.com/

      System information as of Wed Dec 28 16:02:35 UTC 2016

      System load:  0.0                Users logged in:        1
      Usage of /:   13.2% of 39.34GB   IP address for eth0:    10.0.2.15
      Memory usage: 49%                IP address for eth1:    10.100.199.200
      Swap usage:   0%                 IP address for docker0: 172.17.0.1
      Processes:    105

**Comment by vfarcic** [comment]
Can you confirm that you are running those commands from inside the `dev` VM. If you are, can you please send me the directory you're in and the list of files?

**Comment by tompurl** [comment]
Thank you for your quick response! Yes, I am running the `docker` and `docker-compose` commands from within the dev vm. Here's everything:

    $ vagrant ssh dev
    Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-101-generic x86_64)

     * Documentation:  https://help.ubuntu.com/

      System information as of Wed Dec 28 16:02:51 UTC 2016

      System load:  0.0                Users logged in:        1
      Usage of /:   13.2% of 39.34GB   IP address for eth0:    10.0.2.15
      Memory usage: 49%                IP address for eth1:    10.100.199.200
      Swap usage:   0%                 IP address for docker0: 172.17.0.1
      Processes:    105

      Graph this data and manage this system at:
        https://landscape.canonical.com/

      Get cloud support with Ubuntu Advantage Cloud Guest:
        http://www.ubuntu.com/business/services/cloud

    New release '16.04.1 LTS' available.
    Run 'do-release-upgrade' to upgrade to it.


    Last login: Wed Dec 28 16:02:51 2016 from 10.0.2.2
    vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant
    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo docker-compose -f docker-compose-dev.yml run feTestsLocal                                            
    WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
    >>> NPM is broken (again) so front-end tests are temporarily disabled.
    mongod --help for help and startup options
    Wed Dec 28 16:11:51.980 [initandlisten] MongoDB starting : pid=5 port=27017 dbpath=/data/db/ 64-bit host=232bfb94df8f
    Wed Dec 28 16:11:52.020 [initandlisten] db version v2.4.10
    Wed Dec 28 16:11:52.020 [initandlisten] git version: nogitversion
    Wed Dec 28 16:11:52.022 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
    Wed Dec 28 16:11:52.022 [initandlisten] allocator: tcmalloc
    Wed Dec 28 16:11:52.022 [initandlisten] options: {}
    Wed Dec 28 16:11:52.036 [initandlisten] journal dir=/data/db/journal
    Wed Dec 28 16:11:52.036 [initandlisten] recover : no journal files present, no recovery needed
    Wed Dec 28 16:11:52.091 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
    Wed Dec 28 16:11:52.091 [FileAllocator] creating directory /data/db/_tmp
    Wed Dec 28 16:11:52.092 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0 secs
    Wed Dec 28 16:11:52.104 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
    Wed Dec 28 16:11:52.113 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.009 secs
    Wed Dec 28 16:11:52.115 [initandlisten] waiting for connections on port 27017
    Wed Dec 28 16:11:52.116 [websvr] admin web console waiting for connections on port 28017
    [info] Loading project definition from /source/project
    [info] Set current project to books-ms (in build file:/source/)
    [info] Compiling 2 Scala sources to /source/target/scala-2.10/classes...
    [info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
    [info]   Compilation completed in 22.622 s
    [info] Running com.technologyconversations.api.Service 
    16:13:05.194 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Registering Scala Conversions.
    16:13:05.214 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Deserializers for Scala Conversions registering
    16:13:05.215 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Serializers for Scala Conversions registering
    16:13:05.215 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up OptionSerializer
    16:13:05.217 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaProductSerializer
    16:13:05.223 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaCollectionSerializer
    16:13:05.226 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaRegexSerializers
    16:13:05.226 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Hooking up scala.util.matching.Regex seri
    16:13:05.226 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Hooking up scala.util.matching.Regex serializer
    16:13:05.227 [routingSystem-akka.actor.default-dispatcher-3] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Reached base registration method on MongoConversionHelper.
    [INFO] [12/28/2016 16:13:05.269] [routingSystem-akka.actor.default-dispatcher-4] [akka://routingSystem/user/IO-HTTP/listener-0] Bound to /0.0.0.0:8080
    [INFO] [12/28/2016 16:13:05.273] [routingSystem-akka.actor.default-dispatcher-2] [akka://routingSystem/deadLetters] Message [akka.io.Tcp$Bound] from 
    Actor[akka://routingSystem/user/IO-HTTP/listener-0#-1817325099] to Actor[akka://routingSystem/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
    Wed Dec 28 16:13:06.206 [initandlisten] connection accepted from 127.0.0.1:54534 #1 (1 connection now open)

Then it just hangs there. Here's my host OS:

    $ uname -a
    Linux pam 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by tompurl** [comment]
Whoops, hold the phone. I thought I ran `vagrant up dev` but I only ran `vagrant up`. Let me try this again. If it works now I'll close this issue. Sorry for the confusion.

**Comment by tompurl** [comment]
Ok, after finally running `vagrant up dev` and then `vagrant ssh dev` I'm seeing the following:

    $ vagant ssh dev
    Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-101-generic x86_64)

     * Documentation:  https://help.ubuntu.com/

      System information as of Wed Dec 28 16:25:57 UTC 2016

      System load:  0.83              Processes:           79
      Usage of /:   3.6% of 39.34GB   Users logged in:     0
      Memory usage: 6%                IP address for eth0: 10.0.2.15
      Swap usage:   0%

      Graph this data and manage this system at:
        https://landscape.canonical.com/

      Get cloud support with Ubuntu Advantage Cloud Guest:
        http://www.ubuntu.com/business/services/cloud

    0 packages can be updated.
    0 updates are security updates.

    New release '16.04.1 LTS' available.
    Run 'do-release-upgrade' to upgrade to it.


    /usr/bin/xauth:  file /home/vagrant/.Xauthority does not exist
    vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant/
    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo docker-compose -f docker-compose-dev.yml run feTestsLocal
    WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
    Pulling feTestsLocal (vfarcic/books-ms-tests:latest)...
    latest: Pulling from vfarcic/books-ms-tests
    51f5c6a04d83: Pull complete
    ...
    23c20a35bb49: Pull complete
    Digest: sha256:c7d08b3eb053cc975137ccd042b7009c6bfc80ed1e996a42791edea83d190ad5
    Status: Downloaded newer image for vfarcic/books-ms-tests:latest
    >>> NPM is broken (again) so front-end tests are temporarily disabled.
    mongod --help for help and startup options
    Wed Dec 28 16:39:48.670 [initandlisten] MongoDB starting : pid=5 port=27017 dbpath=/data/db/ 64-bit host=22a9ede64a7a
    Wed Dec 28 16:39:48.687 [initandlisten] db version v2.4.10
    Wed Dec 28 16:39:48.687 [initandlisten] git version: nogitversion
    Wed Dec 28 16:39:48.687 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
    Wed Dec 28 16:39:48.688 [initandlisten] allocator: tcmalloc
    Wed Dec 28 16:39:48.688 [initandlisten] options: {}
    Wed Dec 28 16:39:48.694 [initandlisten] journal dir=/data/db/journal
    Wed Dec 28 16:39:48.697 [initandlisten] recover : no journal files present, no recovery needed
    Wed Dec 28 16:39:48.791 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
    Wed Dec 28 16:39:48.791 [FileAllocator] creating directory /data/db/_tmp
    Wed Dec 28 16:39:48.792 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0 secs
    Wed Dec 28 16:39:48.797 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
    Wed Dec 28 16:39:48.798 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0 secs
    Wed Dec 28 16:39:48.799 [initandlisten] waiting for connections on port 27017
    Wed Dec 28 16:39:48.799 [websvr] admin web console waiting for connections on port 28017
    [info] Loading project definition from /source/project
    [info] Set current project to books-ms (in build file:/source/)
    [info] Compiling 2 Scala sources to /source/target/scala-2.10/classes...
    [info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
    [info]   Compilation completed in 23.109 s
    [info] Running com.technologyconversations.api.Service 
    16:41:03.360 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Registering Scala Conversions.
    16:41:03.402 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Deserializers for Scala Conversions registering
    16:41:03.403 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Serializers for Scala Conversions registering
    16:41:03.404 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up OptionSerializer
    16:41:03.406 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaProductSerializer
    16:41:03.410 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaCollectionSerializer
    16:41:03.414 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaRegexSerializers
    16:41:03.416 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Hooking up scala.util.matching.Regex serializer
    16:41:03.429 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Reached base registration method on MongoConversionHelper.
    Wed Dec 28 16:41:04.986 [initandlisten] connection accepted from 127.0.0.1:51798 #1 (1 connection now open)
    [INFO] [12/28/2016 16:41:05.203] [routingSystem-akka.actor.default-dispatcher-2] [akka://routingSystem/user/IO-HTTP/listener-0] Bound to /0.0.0.0:8080
    [INFO] [12/28/2016 16:41:05.207] [routingSystem-akka.actor.default-dispatcher-5] [akka://routingSystem/deadLetters] Message [akka.io.Tcp$Bound] from Actor[akka://routingSystem/user/IO-HTTP/listener-0#1205932392] to Actor[akka://routingSystem/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

Then there's no more output from the docker image port 8080 doesn't accept connections.

**Comment by edwize** [comment]
tompurl:
Use "run --service-ports" instead of "run" which doesn't expose the ports. The doc's say to use "up" instead, but that did not work for this docker-compose file.
Try "docker-compose -f docker-compose-dev.yml run --service-ports feTestsLocal"

I'm using VirtualBox and also had to map the VM's port 8080 to my laptops 9080. After that I got the Applications form at http://127.0.0.1:9080/components/tc-books/demo/index.html

**Comment by vfarcic** [comment]
@tompurl @edwize is right. The `--service-ports` argument is missing. I updated the LeanPub version of the book. Amazon eBook update will be available soon.
