### ISSUE TITLE
Error: Could not retrieve sbt 0.13.13 The command '/bin/sh -c cd /source && sbt update' returned a non-zero code: 1

### ISSUE THREAD

**Issue by goutham27** [vfarcic/books-ms#27]
Hi victor,

I am having below error at page 66. Can you please let me know how to fix it.

https://gist.github.com/goutham27/7f575de654f0aed8a965aee5f89caa5b

Thank you

Goutham

**Comment by vfarcic** [comment]
Sorry for not responding earlier.

Judging by the logs, the problem was probably temporary and related to packages repository. Can you please try again? If it still fails, can you confirm that you are not behind a firewall?

**Comment by vfarcic** [comment]
Can you please let me know if the problem persists or I can close this ticket.
