### ISSUE TITLE
"docker exec -it books-ms bash" fails

### ISSUE THREAD

**Issue by ghost** [vfarcic/books-ms#28]
I am currently following the DevOps 2.0 toolkit book and on page 72 there is a command described 
`docker exec -it books-ms bash`. When trying to run that command i get the following error:
`rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\"\n"`

I also tried executing it with `sudo` and with `/bin/bash`.

I think this has something to do with changing from `debian:jessie` to `openjdk:8-jdk-alpine`. Is there any other way to get in to the container? Or do i need another base container?

**Comment by vfarcic** [comment]
Sorry for that. There was a pull request a few days ago that optimized the image. However, I missed to notice this problem. I just reverted it to the previous version. Can you please try it out and let me know if it works correctly?

**Comment by ghost** [comment]
The commando indeed works again. Thanks for reverting.
