### ISSUE TITLE
ansible fails while bootstrapping the dev VM

### ISSUE THREAD

**Issue by yasenmih** [vfarcic/books-ms#30]
I am issuing 'vagrant up dev' and everything works until ansible tries to install docker-compose. I get:

==> dev: TASK [docker : Docker Compose is present] **************************************
==> dev: fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for github-cloud.s3.amazonaws.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Comment by vfarcic** [comment]
Docker Compose version was very old and not available from Docker any more. I updated it to the latest. Can you please try it out and let me know whether it works?

**Comment by yasenmih** [comment]
Thanks. It works like a charm.
