### ISSUE TITLE
Running chapter 1 docker-compose networking issue

### ISSUE THREAD

**Issue by majorgilles** [vfarcic/books-ms#31]
Hello, 

when trying to run the docker-compose-dev.yml file given the instructions in the book without a vagrant vm, 
the application (feTestsLocal target) is indeed running but  is assigned to the bridge network. 

I managed to inspect the running container's ip address by inspecting the bridge but this is confusing as there was a bookms_default network already in place.

The final ip was 172.17.0.2:8080. Strangely, the 8080 port, which seems correctly defined in the compose file, doesn't seem to resolve correctly by using localhost:8080 (this is the really confusing part for me...)

If using vagrant is absolutely required, this is a mistake on my part, but I'm sure some other people already have all software in place and would wish to use this option.

Best regards,
Gilles Major

**Comment by vfarcic** [comment]
You can, for example, specify in a compose file that the network should be overlay (or any other type baked into Docker or added through a plugin.

Vagrant is used in the book only as an easy way to do examples that would work for everyone. The principles from the book (not necessarily the exactly same commands), should work on any Linux platform that has Docker Engine.

What are you using in this example? Docker for Win/Mac, Docker Machine, ....?

Can you join http://slack.devops20toolkit.com/ and ping me? We can have a chat, share your screen, and figure out the problem together.

**Comment by vfarcic** [comment]
Please let me know if the previous set of comments answered your questions and whether we can close this issue.

**Comment by majorgilles** [comment]
Hello Victor, sorry for not answering sooner and thank you for taking the time to answer issues.

Yes you can close the ticket. My comment was just that port 8080 was not being mapped to my docker host's 8080 port when running the feTestsLocal target, although it is correctly set in the docker-compose file. I don't know yet why it does that, but this is not a blocker for me.
