### ISSUE TITLE
Devops Toolkit Book Reference Error

### ISSUE THREAD

**Issue by ephur** [vfarcic/books-ms#32]
Page 285 of the book is about docker and overlay networks. It's referencing: 
[docker-compose-swarm-v2](https://github.com/vfarcic/books-ms/blob/master/docker-compose-swarm-v2.yml)

However this file does not contain any sort of docker network definition.

**Comment by vfarcic** [comment]
When a Docker Compose project is created, `default` network is created and envelops all services inside that project. You can notice that from the output. There should be a message like "creating network...".

I have the manuscript in Markdown and there are many editions of the book so a page number is not an easy way to find that part. Can you please let me know what is the chapter/subchapter? That way I can search for it in the manuscript and give a more precise answer and/or improve the book.

**Comment by vfarcic** [comment]
Please let me know if the previous comment answers your question and whether this issue can be closed.

**Comment by ephur** [comment]
Sorry for the delay, thanks for following up. The section of the book is:
Deploying with Docker Swarm and Docker Networking inside of Clustering and Scaling Services

The referenced docker compose definition works fine, but the text of the book is referring to the contents of the file. It appears to be showing the contents of docker-compose-swarm.yml, which contains the line:   net: books-ms

That is not present in -v2  

It's a very minor error, and I appreciated this book very much. I just got a little confused as I had been going through the source and saw the default network created, I just wasnt's sure if the net: books-ms party was important (later learned it wasn't, but caused a tiny bit of confusion on the first pass).

**Comment by vfarcic** [comment]
The correct file is `docker-compose-swarm.yml` (not `docker-compose-swarm-v2.yml`).

Corrected version will be available on LeanPub in a few minutes. The other vendors are much slower but it'll get there as well. 

Thank you for spotting this problem. I really appreciate it.
