### ISSUE TITLE
Dockerfile.test error

### ISSUE THREAD

**Issue by rogerscuall** [vfarcic/books-ms#33]
I'm using your code while reading your book, in page 67 you have:
```
docker build \
       -f Dockerfile.test \
       -t 10.100.198.200:5000/books-ms-tests \
       .
```
And in my case is failing with this error:
```
E: Unable to correct problems, you have held broken packages.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sbt : Depends: openjdk-8-jdk but it is not installable
The command '/bin/sh -c apt-get update &&     apt-get -y --fix-missing install wget bzip2 make g++ &&     apt-get -y --force-yes --fix-missing install --no-install-recommends mongodb nodejs git sbt xvfb firefox google-chrome-stable &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
can you point me in the right direction?

**Comment by JoeDuncko** [comment]
I'm having this issue as well. I ran it successfully the other week I think.

**Comment by rogerscuall** [comment]
Same here, last Friday worked perfectly.

**Comment by JoeDuncko** [comment]
I actually can't run `sudo apt-get install openjdk-8-jdk` either - I'm assuming that's related. It says that it can't find the package. Hm. Did they remove it? Even so, I added another repository that does have `openjdk-8-jdk` via the directions at http://ubuntuhandbook.org/index.php/2015/01/install-openjdk-8-ubuntu-14-04-12-04-lts/ and was able to install it after I did that, but 

```
docker build \
       -f Dockerfile.test \
       -t 10.100.198.200:5000/books-ms-tests \
       .
```

still won't run successfully and spits out the same error as above. I'm giving up for now.

**Comment by CameronEzraJones** [comment]
I was having the same problem. Here's what I did to get it working for me

1. Change the docker image being used on line 1 from `debian:jessie` to `ubuntu:16.04`
2. On line 12, you should change `https://deb.nodesource.com/setup_0.12` to `https://deb.nodesource.com/setup_6.x`. When I fixed the issue that @rogerscuall described, I ran into an issue with npm that seemed to stem from this old version of node. This uses the latest LTS version.
3. On line 27, add `--force-all` as a flag for the `dpkg` command. When `dpkg` tries to install scala, it's going to want to install `openjdk-7-jdk`, which it was unable to find. The `--force-all` command allows the installation of scala without having to worry about the broken dependency.

I hope this works for you as well. I'm open to any better solutions.

**Comment by LukaszHerbet** [comment]
Another workaround that worked for me was changing the version of sbt. The newest version `0.13.15` released few days ago causes the problem. Version `0.13.13` (that was the latest in the repo till ~2017-04-09) doesn't depends on `openjdk-8-jdk`.

Just change `sbt` to `sbt=0.13.13` in line 21.

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I was offline for over a week. This week I'm at DockerCon and will have a very limited availability. Could you make a PR?
