### ISSUE TITLE
Jenkins multibranch pipelines don't work as expected

### ISSUE THREAD

**Issue by LukaszHerbet** [vfarcic/books-ms#36]
Going through the book I found that in Jenkins multibranch pipelines like `books-ms-multibranch` or `books-ms-blue-green` for all of the branches code from branch `master` is being checked out and build.

I supose that the intention was to checkout and build the code from the same branch that Jenkinsfile is located. 

When using line
`git url: "https://github.com/vfarcic/${serviceName}.git"`
in Jenkinsfile, code from `master` branch is checked out by default no matter in which branch the file is located (I suspect that code from Jenkinsfile was working as expected with older versions of Git plugin / Git client plugin). It can be seen in console output of Git step. All commands from Jenkinsfile used after this line (i.e. `flow.buildTests(...)`) use the code checked out from `master`.

Please consider using one of the following lines (instead of the one used now)
`git url: "https://github.com/vfarcic/${serviceName}.git", branch: "${env.BRANCH_NAME}"`
or
`checkout scm`
to checkout the code from the same branch that Jenkinsfile.

**Comment by vfarcic** [comment]
You're right. `checkout scm` is the correct step. I updated the repo.

Thank you for noticing this and letting me know.
