### ISSUE TITLE
Dockerfile.text Unexpected token ILLEGAL error p66

### ISSUE THREAD

**Issue by dtdenver** [vfarcic/books-ms#41]
I have failed twice on this command, page 66:
docker build \
     -f Dockerfile.test \
     -t 10.100.198.200:5000/books-ms-tests \
     .

Output below appears to not like the 0 in 0o755, but where is the file?  How do I fix this?

> node scripts/postinstall.js

/source/client/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:128
        fs.chmod(bin, 0o755, function (err) {
                               ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/source/client/node_modules/web-component-tester/node_modules/wct-sauce/lib/sauce.js:15:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm WARN optional dep failed, continuing wct-sauce@2.0.0-pre.1

**Comment by vfarcic** [comment]
Can you send me the name of the chapter/subchapter you're stuck in? There are many editions of the book and page numbers tend to vary greatly from one to another.

I'll start by rerunning the commands. If it fails on my laptop, something recently changed in one of the packages and I'll fix it. If, on the other hand, it works on my laptop, we'll know that we should look into your computer while searching for the culprit.

**Comment by dtdenver** [comment]
Chapter title is Implementation of the Deployment Pipeline: Initial Stages

Subtitle is Running Pre-Deployment Tests, Compiling, and Packaging the Code


________________________________

**Comment by vfarcic** [comment]
I just rerun that chapter until that command. I saw the same entry in the logs but, in my case, it continued building the image meaning that it was only a warning (`docker build` fails if a command throws an error). Can you please let me know whether in your case the build stopped or it continued as well?

**Comment by dtdenver** [comment]
Thanks for checking this.  I see that the last line does say WARN.  I reran the process a couple times, I see that my version of node is not current.  I am not able to complete the command, it hangs around this statement and I have to ctrl-c out.  I will update node and see if that helps.


thanks again,




________________________________

**Comment by vfarcic** [comment]
Dockerfile is a bit old and it deserves an update. Please do a PR if you change anything that might be useful for other.

**Comment by pioneerit** [comment]
It is a problem of using NPM, never knows what is inside:
https://github.com/bermi/sauce-connect-launcher/blob/master/lib/sauce-connect-launcher.js#L128

Bug added in sauce-connect-launcher@1.2.2.
Version 1.2.0 should be fine, by I don't know how to force older version.

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I'm on a business trip with almost no free time. I'll can go through this during next week. Please let me know if you find out more until then.

**Comment by naslanidis** [comment]
I am having a similar issue at the same point of the book:

docker build \
-f Dockerfile.test \
-t 10.100.198.200:5000/books-ms-tests \

/source/client/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:128
        fs.chmod(bin, 0o755, function (err) {
                      ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/source/client/node_modules/web-component-tester/node_modules/wct-sauce/lib/sauce.js:15:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm WARN optional dep failed, continuing wct-local@2.0.15
npm WARN optional dep failed, continuing wct-sauce@2.0.0-pre.1
npm ERR! Linux 3.13.0-119-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.18
npm ERR! npm  v2.15.11

npm ERR! shasum check failed for /tmp/npm-5-5dde0287/registry.npmjs.org/rx/-/rx-4.1.0.tgz
npm ERR! Expected: a5f13ff79ef3b740fe30aa803fb09f98805d4782
npm ERR! Actual:   01d58dae44391a7ec8a83883d3be4edf47cfbbf0
npm ERR! From:     https://registry.npmjs.org/rx/-/rx-4.1.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /source/client/npm-debug.log
The command '/bin/sh -c cd /source/client && npm install' returned a non-zero code: 1

**Comment by pioneerit** [comment]
@naslanidis I've replaced node version, no sure if it doesn't break something else:
For example in Dockerfile.test:
`RUN curl -sL https://deb.nodesource.com/setup_0.12 | bash -`
to
`RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -`

**Comment by vfarcic** [comment]
I updated NodeJS version as well as of the `test-fixture` library. Can you please pull the latest code, try again and let me know whether it works?

**Comment by naslanidis** [comment]
@vfarcic I can confirm that the build now succeeds. Thank you so much for addressing this as I'm sure you're busy.

**Comment by vfarcic** [comment]
Great to hear that @naslanidis. Closing the issue...
