### ISSUE TITLE
Issues with pulling image from local repository

### ISSUE THREAD

**Issue by eikster-dk** [vfarcic/books-ms#42]
Hello,

I'm following the book chapter by chapter, but skipped the first two, since i already knew about it, so i thought i would quickly read it through without doing the "hands on" part. 

I'm at the End of "proxy services" chapter, we destroy the vm's by using "vagrant destroy -f", and in the next chapter ("implementing of the deployment pipeline: The late stages") we spin up the cd and prod vms again. Then we run the ansible/prod2.yml on prod vm and download the docker-compose from books-ms/master. 

As soon as i run the "docker-compose up -d app" i get the following:

`
vagrant@cd:~$ export DOCKER_HOST=tcp://prod:2375
vagrant@cd:~$ docker-compose up -d app
Pulling db (mongo:latest)...
latest: Pulling from library/mongo
56c7afbcb0f1: Pull complete
ac4863389b54: Pull complete
fccbd1684456: Pull complete
5565b5f177e7: Pull complete
b00971241c47: Pull complete
c0300dc07374: Pull complete
b93b8ba2b93b: Pull complete
661362338965: Pull complete
fa170e22de2e: Pull complete
22670c2d1be4: Pull complete
2efb0cd1fb79: Pull complete
Digest: sha256:2dd49be30907c901a3312f0452ba57128ca6449378cfe9d19ad01732a873d3bd
Status: Downloaded newer image for mongo:latest
Pulling app (10.100.198.200:5000/books-ms:latest)...
Pulling repository 10.100.198.200:5000/books-ms
ERROR: Error: image books-ms:latest not found
`

Am i missing something from the first chapters? Do I actually have to do a build of the books-ms before the images exist in the local repository? 

Have i misunderstood the "vagrant destroy -f" command ? Because i thought it actually wiped the whole vm from existence including the vm's current state.

Everytime i try to spin up the "docker-compose up -d app" command i always get the image not found error.

**Comment by vfarcic** [comment]
The reason for that error is probably caused by not pushing the image to the registry. Chapter "Implementation of the Deployment Pipeline: Initial Stages > Pushing Containers to the Registry" contains the command `docker push 10.100.198.200:5000/books-ms` that, after the image is built, sends it to the registry. Since registry is persistent on your laptop, those files are preserved even after destroying VMs.

Please let me know if running the commands from that chapter (at least build and push) solves the problem.

**Comment by eikster-dk** [comment]
I ran the "Preload_cd.sh" script and everything started to work! 

Thanks Victor, I have read lots of tech books and this one is one of the most awesome and funny books to read! Keep up the good work ❤️

**Comment by vfarcic** [comment]
You're very welcome. I'm glad it worked out :)

Feel free to get back to me if you encounter any other problem. You  might
want to join http://slack.devops20toolkit.com/ as well. There are quite a
few of us there discussing and solving each other problems.

**Comment by eikster-dk** [comment]
Awesome, thanks mate!

I will close the "issue" :)
