### ISSUE TITLE
target directory is missing

### ISSUE THREAD

**Issue by steku** [vfarcic/books-ms#44]
Causes books-ms docker build to fail

**Comment by vfarcic** [comment]
Is your target directory mounted inside the VM? Please enter it and check the contents of the `/vagrant` dir. It should contain the files from your current host directory. Also, please confirm that you created VMs inside your user's (sub)directory.

**Comment by steku** [comment]
I had the cd host up and was logged in. I can't get back to that point right now because i deleted the cd host. If you try to build the docker container for book-ms the build will not finish due to the target directory being missing.

**Comment by steku** [comment]
vagrant@cd:~/books-ms$ docker build  -t 10.100.198.200:5000/books-ms .
Sending build context to Docker daemon  3.217MB
Step 1/11 : FROM java
latest: Pulling from library/java
5040bd298390: Pull complete 
fce5728aad85: Pull complete 
76610ec20bf5: Pull complete 
60170fec2151: Pull complete 
e98f73de8f0d: Pull complete 
11f7af24ed9c: Pull complete 
49e2d6393f32: Pull complete 
bb9cdec9c7f3: Pull complete 
Digest: sha256:c1ff613e8ba25833d2e1940da0940c3824f03f802c449f3d1815a66b7f8c0e9d
Status: Downloaded newer image for java:latest
 ---> d23bdf5b1b1b
Step 2/11 : MAINTAINER Viktor Farcic "viktor@farcic.com"
 ---> Running in c5a10cc6fdef
 ---> c0c9d5a7e06c
Removing intermediate container c5a10cc6fdef
Step 3/11 : ENV DB_DBNAME books
 ---> Running in 79d2b73d58ba
 ---> 52cceb26d097
Removing intermediate container 79d2b73d58ba
Step 4/11 : ENV DB_COLLECTION books
 ---> Running in ea71a1b3dc74
 ---> 86d1ac22f2fa
Removing intermediate container ea71a1b3dc74
Step 5/11 : ENV DB_HOST localhost
 ---> Running in 737d9e1af00d
 ---> f748ae41ad2d
Removing intermediate container 737d9e1af00d
Step 6/11 : COPY run.sh /run.sh
 ---> cfc4886ea57c
Removing intermediate container 0fedc48601bc
Step 7/11 : RUN chmod +x /run.sh
 ---> Running in 4bcc1f1e56af
 ---> bbfd4c4a15d9
Removing intermediate container 4bcc1f1e56af
Step 8/11 : COPY target/scala-2.10/books-ms-assembly-1.0.jar /bs.jar
lstat target/scala-2.10/books-ms-assembly-1.0.jar: no such file or directory

**Comment by steku** [comment]
i was able to get this up and running by copying the target directory to the books-ms repository located in the cd vm.

**Comment by vfarcic** [comment]
Copying the files (or cloning them from the repo) does the trick. It still does not fix the problem that your host files are not mounted inside the VM. But, if copying the files works for you...
