### ISSUE TITLE
self.client = docker.Client(base_url=docker_url,\nAttributeError: 'module' object has no attribute 'Client'\n", "module_stdout": "", "msg": "MODULE FAILURE"}

### ISSUE THREAD

**Issue by denpear** [vfarcic/books-ms#47]
Please, give me a prompt how to overcome error below:

 self.client = docker.Client(base_url=docker_url,\nAttributeError: 'module' object has no attribute 'Client'\n", "module_stdout": "", "msg": "MODULE FAILURE"}

I'm just trying to go through Setting Up Jenkins with Ansible within Continuous Integration (CI), Delivery and Deployment (CD) Tools (page 201):

First command was ok:
ansible-playbook /vagrant/ansible/jenkins-node.yml \
 -i /vagrant/ansible/hosts/prod

But at second one I've got an erroк
![image](https://cloud.githubusercontent.com/assets/20821041/26583834/64ff6c02-454f-11e7-9e50-a2ccb229f021.png)

Thank you

**Comment by vfarcic** [comment]
I just rerun all the commands from that chapter and did not hit the same problem. One possibility is that there was a temporary glitch in Docker Hub. Can you please re-run the commands? When you reach the command that failed, please add `-vvvv`. That will give us more information about the failure if it happens again.

**Comment by denpear** [comment]
Thank you your reply.
I continued investigating. And now attach a new pic
![image](https://cloud.githubusercontent.com/assets/20821041/26712496/ca53fed4-476f-11e7-957b-4c437eeb30cb.png)

**Comment by vfarcic** [comment]
I remember that error from long ago but it was fixed and no one reported it for almost a year. Can we have a chat and share your screen?

**Comment by denpear** [comment]
Yes, we can
Which one chat do prefer? I have never done  it before. So let me know  your choice of chat. 
Suggest the most convenient option for you. Thank you

**Comment by vfarcic** [comment]
Hi,

Skype or HangOuts should do just fine. What is your timezone?

**Comment by denpear** [comment]
Hi, HangOut should be great!

**Comment by vfarcic** [comment]
What is your timezone? One option would be Tuesday 22h CEST but I'm not sure what would that translate in your case.

**Comment by denpear** [comment]
Ok, my timezone UTC/GMT +3
But how did khow?

**Comment by denpear** [comment]
I mean CEST...Where did see it?

**Comment by vfarcic** [comment]
In that case, 22h CEST might be a bit too late for you. That would be midnight your time. The alternative is Wednesday 4pm CEST. Feel free to choose any of the two and send me an calendar invite.

**Comment by vfarcic** [comment]
I think we fixed or, to be more concrete, found a workaround through a chat. Please reopen if that's not true.

**Comment by denpear** [comment]
Yes, thank you, Viktor. I thank you very much for your cooperation.

**Comment by fvlad** [comment]
Could you please give a hint for a workaround?

**Comment by denpear** [comment]
It was easy. We make a new git clone in new folder and start a tutorial from the very beginnig. Vagrant has to work from new folder.
