### ISSUE TITLE
docker run for books-db throwing error

### ISSUE THREAD

**Issue by dtdenver** [vfarcic/books-ms#48]
On page 72, in Implementation of the Deployment Pipeline Initial Stages, this command:

docker run -d --name books-ms \
   -p 8080:8080 \
   --link books-db:db \
  10.100.198.200:5000/books-ms

I have this error - maybe 2 errors:

Unable to find image '10.100.198.200:5000/books-ms:latest' locally (might be error #1?)
docker: Error response from daemon: Get https://10.100.198.200:5000/v1/_ping: dial tcp 10.100.198.200:5000: getsockopt: connection refused. (Definitely error, why https instead of http?)
See 'docker run --help'.

**Comment by vfarcic** [comment]
`https` is the default connection protocol with Docker registries.

Can you please confirm that registry is running and that you pushed the image? If it is running, please confirm that you don't have a corporate proxy that might interfere with connections.

**Comment by dtdenver** [comment]
Your suggestion put me on the right path to figure this out.  I ran 'docker images' and did not see the books-ms image on 10.100.198.200:5000/books-ms.


I ran 'ifconfig' and saw that eth1 is running on 10.100.199.200.  I ran  'docker build' again with that IP then 'docker run' command for books-ms and it is now working.


I do have one more question, does 'docker build' command also include a push to private registry, like includes 'docker push'?


Thanks


dt


________________________________

**Comment by vfarcic** [comment]
Docker build does not push to registry. It only builds Docker image (e.g. `docker image build -t my-image .`). You need to push it through a separate command (e.g. `docker image push my-image`).

I'll close the issue since the original problem is fixed. Feel free to reopen it if you feel I misunderstood the problem.
