### ISSUE TITLE
docker push getsockopt: connection refused

### ISSUE THREAD

**Issue by dtdenver** [vfarcic/books-ms#49]
page 77 this command
docker push 10.100.198.200:5000/books-ms

results in this error message:
The push refers to a repository [10.100.198.200:5000/books-ms]
Get https://10.100.198.200:5000/v1/_ping: dial tcp 10.100.198.200:5000: getsockopt: connection refused

running in vagrant vm
docker ps -a shows:
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                    NAMES
2d83b70ad1da        10.100.198.200:5000/books-ms   "/run.sh"                20 minutes ago      Up 3 minutes        0.0.0.0:8080->8080/tcp   books-ms
1a8099b77735        mongo                          "docker-entrypoint..."   21 minutes ago      Up 3 minutes        27017/tcp                books-db

**Comment by vfarcic** [comment]
Seems that registry is not running in 10.100.198.200. Can you please tell me the name of the chapter/subchapter? Page numbers change from one edition to another...

**Comment by dtdenver** [comment]
Thanks (again), yes the registry was not running because I was in the wrong Vagrant vm, I was in dev and should have been in cd.  I went back and made sure I paid attention to all steps and was able to complete "Implementation of the Deployment Pipeline: Initial Stages"


DT


________________________________

**Comment by vfarcic** [comment]
That's great to hear :)
