### ISSUE TITLE
Step 9 fails when building container books-ms

### ISSUE THREAD

**Issue by juhamk** [vfarcic/books-ms#5]
docker build -t 10.100.198.200:5000/books-ms . causes:

Step 9 : COPY target/scala-2.10/books-ms-assembly-1.0.jar /bs.jar
lstat target/scala-2.10/books-ms-assembly-1.0.jar: no such file or directory

Whole target-folder seem to be missing...

**Comment by vfarcic** [comment]
The target folder with the jar is created through tests that are run before
that command. Can you send me the log from runnig tests container?

On Sun, May 29, 2016, 23:19 juhamk notifications@github.com wrote:

> docker build -t 10.100.198.200:5000/books-ms . causes:
> 
> Step 9 : COPY target/scala-2.10/books-ms-assembly-1.0.jar /bs.jar
> lstat target/scala-2.10/books-ms-assembly-1.0.jar: no such file or
> directory
> 
> Whole target-folder seem to be missing...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/vfarcic/books-ms/issues/5, or mute the thread
> https://github.com/notifications/unsubscribe/AFc5A3AF8GPP6z6QqYfS6GSQWggFRGYYks5qGgLogaJpZM4IpYcG
> .
> 
> ## 
> 
> Viktor Farcic

Blog:
TechnologyConversations.com

Books:
The DevOps 2.0 Toolkit (http://www.amazon.com/dp/B01BJ4V66M or
https://leanpub.com/the-devops-2-toolkit)
Test-Driven Java Development (
http://www.amazon.com/Test-Driven-Java-Development-Viktor-Farcic-ebook/dp/B00YSIM3SC
)

**Comment by eriksays** [comment]
Victor,
[you can ignore this message. looks like it was running out of diskspace on my side]

I was experiencing the same issue and realized that I needed to rerun the tests.

I keep getting a file permissions error "-bash: cannot create temp file for here-document: Read-only file system"

I successfully ran the first test "docker build Dockerfile.test ...." -- it took awhile but worked
second line "docker-compose -f ...." first ran into an issue "An HTTP request took too long to complete."
on trying to again, I get 'INTERNAL ERROR: cannot create temporary directory' and it seems I've suddenly got file permissions errors.

I don't think this is related to your instructions but a docker issue I'm having in general?

thanks

**Comment by vfarcic** [comment]
This repository is used in quite a few articles and a book I wrote so I'm not sure about the environment you're using to build/run the container. Is it inside a Docker Machine, a Vagrant VM, "real" server, directly on OS...?

**Comment by geekluv** [comment]
victor,

I'm following your devops2 toolkit book (love the book so far).
I'm within ms-lifecycle, have done vagrant ssh cd, and am now trying 'docker-compose -f docker-compose.dev.yml run --rm tests' and am getting this consistently

The DOMAIN variable is not set. Defaulting to a blank string.
Pulling tests (10.100.198.200:5000/books-ms-tests:latest)...
Pulling repository 10.100.198.200:5000/books-ms-tests
ERROR: Error while pulling image: Get http://10.100.198.200:5000/v1/repositories/books-ms-tests/images: dial tcp 10.100.198.200:5000: getsockopt: connection refused

thanks

**Comment by vfarcic** [comment]
Hi,

That command should pull the container from the local registry. The first
thing we should check is whether the registry is running. Can you do
"docker ps -a" and send me the output. If you are available now, we can
connect through Skype or HangOuts and share your screen.

On Mon, May 30, 2016 at 8:49 PM matthew collins notifications@github.com
wrote:

> victor,
> 
> I'm following your devops2 toolkit book (love the book so far).
> I'm within ms-lifecycle, have done vagrant ssh cd, and am now trying
> 'docker-compose -f docker-compose.dev.yml run --rm tests' and am getting
> this consistently
> 
> The DOMAIN variable is not set. Defaulting to a blank string.
> Pulling tests (10.100.198.200:5000/books-ms-tests:latest)...
> Pulling repository 10.100.198.200:5000/books-ms-tests
> ERROR: Error while pulling image: Get
> http://10.100.198.200:5000/v1/repositories/books-ms-tests/images: dial
> tcp 10.100.198.200:5000: getsockopt: connection refused
> 
> thanks
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/vfarcic/books-ms/issues/5#issuecomment-222540371, or mute
> the thread
> https://github.com/notifications/unsubscribe/AFc5Ay0XPwkrUcLJaFdjcSnmBoovTUVxks5qGzE7gaJpZM4IpYcG
> .
> 
> ## 
> 
> Viktor Farcic

Blog:
TechnologyConversations.com

Books:
The DevOps 2.0 Toolkit (http://www.amazon.com/dp/B01BJ4V66M or
https://leanpub.com/the-devops-2-toolkit)
Test-Driven Java Development (
http://www.amazon.com/Test-Driven-Java-Development-Viktor-Farcic-ebook/dp/B00YSIM3SC
)

**Comment by vfarcic** [comment]
The problem was that the VM was stopped and started again. Since it was not provisioned, containers were all stopped as well. The solution is to run "vagrant up --provision".

**Comment by juhamk** [comment]
Great.
Indeed, I missed one step of building books-ms-test and executing the tests, as you stated.
Now it works.

**Comment by drugotosto** [comment]
Hi Victor, I bought your great book "Devops-2.0-toolkit" and I have a problem when I follow the istructions inside the "Setting Up the Development Environment With Vagrant and Docker" chapter.

First of all I run the VM and building the Docker image by the command:
<code>sudo docker build -t vfarcic/books-ms-tests -f Dockerfile.test . </code>

After I had a problem when i tried running either the command:
<code>sudo docker-compose  -f docker-compose-dev.yml run --service-ports feTestsLocal</code>
or 
<code>sudo docker-compose -f docker-compose-dev.yml run testsLocal</code>

I got the following messages:

"WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60). "

When i run the command <code>docker ps</code> inside the VM seem that i haven't any running contaniners... 
I am struggling for a solution.... any suggestions? 

Thanks!

**Comment by vfarcic** [comment]
The problem is probably in slow internet connection or something similar that prevents Compose executing the service within the default time (60 seconds). I just added an `.env` file to the repo that changes the timeout to 300 sec. Can you please pull the latest version of `vfarcic/books-ms` repo and try again? This time, there should  be `.env` file in the repo root.

**Comment by drugotosto** [comment]
I pull the latest version of the repository with the <code>.env</code> file and after run the command :
 <code>sudo docker-compose -f docker-compose-dev.yml run testsLocal</code>

I got the following error:
"WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
standard_init_linux.go:178: exec user process caused "no such file or directory"

:(

**Comment by drugotosto** [comment]
I also want to notice that every time I start the VM I run the command: <code>vagrant up --provision</code> and after I always go inside the directory <code>/vagrant</code> of my VM.

**Comment by drugotosto** [comment]
I work on a windows machine with intellijidea.. Could be a git formatting problem replacing LF with CRLF?

**Comment by drugotosto** [comment]
OK I was able to fix my problem! happiness! :) Now i can start running the tests on the VM. I think that the git formatting was the problem...

**Comment by vfarcic** [comment]
Sorry for not responding earlier. Too much work on my side...

I'm glad it worked out :)
