### ISSUE TITLE
Pushing Containers to the Registry

### ISSUE THREAD

**Issue by youssefhatem90** [vfarcic/books-ms#51]
I am following the instructions on page 79 when I try to push the container to the repository 
docker push 10.100.198.200:5000/books-ms

I got the below message ;
The push refers to repository [10.100.198.200:5000/books-ms]
Get https://10.100.198.200:5000/v2/: dial tcp 10.100.198.200:5000: getsockopt: connection refused

I am using Ubuntu 16.04 and Docker version 17.12.0-ce, build c97c6d6
consider the below ;
-------------------------------
root@youssef:~/ms-lifecycle# vagrant status
Current machine states:
cd                        running (virtualbox)

root@youssef:~/ms-lifecycle# docker ps -a

CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                    NAMES
bb38ba61fd25        10.100.198.200:5000/books-ms   "/run.sh"                36 minutes ago      Up 36 minutes       0.0.0.0:8080->8080/tcp   books-ms
30d9760f4fc7        mongo                          "docker-entrypoint.s…"   37 minutes ago      Up 37 minutes       27017/tcp                books-db

vagrant@cd:~$ cat /etc/default/docker 
DOCKER_OPTS="$DOCKER_OPTS --insecure-registry 10.100.198.200:5000 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --registry-mirror=http://10.100.198.20

Kindly support

**Comment by vfarcic** [comment]
You executed `docker ps -a` from your laptop and not from the `cd` VM. Judging from the outputs you sent, you run at least some of the commands from your laptop, instead from the `cd` VM.

**Comment by youssefhatem90** [comment]
sorry , that was right . Now I repeated all the steps in cd VM but still the same issue while pushing to registery
I built the 2 containers books-ms-tests and books-ms as per below output

vagrant@cd:~/books-ms$ docker build -f Dockerfile.test \ -t 10.100.198.200:5000/books-ms-tests .

Sending build context to Docker daemon  43.26MB
Step 1/29 : FROM debian:jessie
 ---> ce40fb3adcc6
Step 2/29 : MAINTAINER Viktor Farcic "viktor@farcic.com"
 ---> Using cache
 ---> 764227b7bd40
Step 3/29 : ENV VERSION 1.0
 ---> Using cache
 ---> 6c7e7bc75016
Step 4/29 : RUN apt-get update
 ---> Using cache
 ---> ae807a165545
Step 5/29 : RUN apt-get -y install curl
 ---> Using cache
 ---> 10aaf3b789b5
Step 6/29 : RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - &&     echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list &&     curl -sL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&     echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list &&     echo "deb http://packages.linuxmint.com debian import" >> /etc/apt/sources.list
 ---> Using cache
 ---> 86399cf7851d
Step 7/29 : RUN apt-get update &&     apt-get -y --fix-missing install wget bzip2 make g++ &&     apt-get -y --force-yes --fix-missing install --no-install-recommends mongodb git sbt=0.13.13 xvfb nodejs firefox google-chrome-stable &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 2034c9b72f8c
Step 8/29 : RUN curl -O -q http://downloads.typesafe.com/scala/2.11.5/scala-2.11.5.deb &&     dpkg -i scala-2.11.5.deb &&     rm scala-2.11.5.deb
 ---> Using cache
 ---> b70aeec4bc10
Step 9/29 : RUN npm install -g gulp bower
 ---> Using cache
 ---> 69308b38197c
Step 10/29 : RUN mkdir /source
 ---> Using cache
 ---> 6cc8098bb936
Step 11/29 : RUN mkdir -p /data/db
 ---> Using cache
 ---> 955df68da2b5
Step 12/29 : ADD project /source/project
 ---> Using cache
 ---> ad8ac10b0ee5
Step 13/29 : ADD build.sbt /source/build.sbt
 ---> Using cache
 ---> 5d21bc98e951
Step 14/29 : ADD client/bower.json /source/client/bower.json
 ---> Using cache
 ---> a426f2aed93f
Step 15/29 : ADD client/gulpfile.js /source/client/gulpfile.js
 ---> Using cache
 ---> 394336bc5515
Step 16/29 : ADD client/package.json /source/client/package.json
 ---> Using cache
 ---> 7119e613a29c
Step 17/29 : ADD client/wct.conf.js /source/client/wct.conf.js
 ---> Using cache
 ---> 48f23ead5647
Step 18/29 : ADD client/test.html /source/client/test.html
 ---> Using cache
 ---> 68c1d5c0bac4
Step 19/29 : ADD run_tests.sh /source/run_tests.sh
 ---> Using cache
 ---> 6c247bef947f
Step 20/29 : RUN cd /source && sbt update
 ---> Using cache
 ---> cac04d5780f3
Step 21/29 : RUN cd /source/client && npm install && bower install --allow-root --config.interactive=false -s
 ---> Using cache
 ---> 9c49f4b12c9c
Step 22/29 : ENV TEST_TYPE "spec"
 ---> Using cache
 ---> 6f99bb322bc0
Step 23/29 : ENV DOMAIN "http://172.17.42.1"
 ---> Using cache
 ---> 75dad27eb689
Step 24/29 : ENV DISPLAY ":1.0"
 ---> Using cache
 ---> 732c4d455694
Step 25/29 : ENV DB_HOST localhost
 ---> Using cache
 ---> f0f72d94ac98
Step 26/29 : WORKDIR /source
 ---> Using cache
 ---> f6129b54bb62
Step 27/29 : VOLUME /source /source/target/scala-2.10 /root/.ivy2/cache /data/db
 ---> Using cache
 ---> 6d65389a3515
Step 28/29 : CMD /source/run_tests.sh
 ---> Using cache
 ---> 4603377494e5
Step 29/29 : EXPOSE 8080
 ---> Using cache
 ---> 0350254fe50c
Successfully built 0350254fe50c
Successfully tagged 10.100.198.200:5000/books-ms-tests:latest

vagrant@cd:~/books-ms$ docker build -t 10.100.198.200:5000/books-ms .

Sending build context to Docker daemon  43.26MB
Step 1/11 : FROM openjdk
 ---> db77212ffe05
Step 2/11 : MAINTAINER Viktor Farcic "viktor@farcic.com"
 ---> Using cache
 ---> c0337b2f105c
Step 3/11 : ENV DB_DBNAME books
 ---> Using cache
 ---> 3f86815388f1
Step 4/11 : ENV DB_COLLECTION books
 ---> Using cache
 ---> 8bab5092cd98
Step 5/11 : ENV DB_HOST localhost
 ---> Using cache
 ---> 4f0fc45623cc
Step 6/11 : COPY run.sh /run.sh
 ---> Using cache
 ---> 76fef3208dfd
Step 7/11 : RUN chmod +x /run.sh
 ---> Using cache
 ---> a247e5486d28
Step 8/11 : COPY target/scala-2.10/books-ms-assembly-1.0.jar /bs.jar
 ---> Using cache
 ---> bcc964861ca0
Step 9/11 : COPY client/components /client/components
 ---> Using cache
 ---> badc86af7cdc
Step 10/11 : CMD /run.sh
 ---> Using cache
 ---> d7a77930e66b
Step 11/11 : EXPOSE 8080
 ---> Using cache
 ---> a7f51fc34802
Successfully built a7f51fc34802
Successfully tagged 10.100.198.200:5000/books-ms:latest

Note : I didn't run the 2 containers as the / disk is Full
vagrant@cd:~/books-ms$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAME

vagrant@cd:~/books-ms$ docker images 
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
10.100.198.200:5000/books-ms         latest              a7f51fc34802        38 minutes ago      776MB
10.100.198.200:5000/books-ms-tests   latest              0350254fe50c        4 hours ago         2.32GB
openjdk                              latest              db77212ffe05        3 days ago          737MB
debian                               jessie              ce40fb3adcc6        4 days ago          123MB



after building the previous containers i tried to push them to the registry then destroying all VMs to save the space but the connection refused as below

vagrant@cd:~/books-ms$ docker push 10.100.198.200:5000/books-ms
The push refers to a repository [10.100.198.200:5000/books-ms]
Put http://10.100.198.200:5000/v1/repositories/books-ms/: dial tcp 10.100.198.200:5000: getsockopt: connection refused

vagrant@cd:~/books-ms$ docker push 10.100.198.200:5000/books-ms-tests
The push refers to a repository [10.100.198.200:5000/books-ms-tests]
Put http://10.100.198.200:5000/v1/repositories/books-ms-tests/: dial tcp 10.100.198.200:5000: getsockopt: connection refused

kindly support

**Comment by vfarcic** [comment]
Seems that you are NOT running the registry so nothing can be pushed. Can you try again but, this time, first destroy the VMs. It should take a short time to get to the same point from scratch.

**Comment by youssefhatem90** [comment]
Sorry for latency . I repeated all the steps and it is working now . thanks for your support
