### ISSUE TITLE
Front End tests are not running

### ISSUE THREAD

**Issue by junaid-ali** [vfarcic/books-ms#52]
Command:
```
$ sudo docker run -it --rm \
   -v $PWD/client/components:/source/client/components \
   -v $PWD/client/test:/source/client/test \
   -v $PWD/src:/source/src \
   -v $PWD/target:/source/target \
   -p 8080:8080 \
   --env TEST_TYPE=watch-front \
   vfarcic/books-ms-tests
```
Output:
```
>> NPM is broken (again) so front-end tests are temporarily disabled.
mongod --help for help and startup options
Tue Mar 13 06:21:45.815 [initandlisten] MongoDB starting : pid=7 port=27017 dbpath=/data/db/ 64-bit host=cb101376f642
Tue Mar 13 06:21:45.815 [initandlisten] db version v2.4.10
........
Tue Mar 13 06:21:45.979 [websvr] admin web console waiting for connections on port 28017
Tue Mar 13 06:21:45.979 [initandlisten] waiting for connections on port 27017
[info] Loading project definition from /source/project
[info] Set current project to books-ms (in build file:/source/)
........
06:22:15.952 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Registering Scala Conversions.
06:22:15.958 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Deserializers for Scala Conversions registering
06:22:15.959 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Serializers for Scala Conversions registering
06:
.........
06:22:15.964 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Hooking up scala.util.matching.Regex serializer
06:22:15.965 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Reached base registration method on MongoConversionHelper.
Tue Mar 13 06:22:16.134 [initandlisten] connection accepted from 127.0.0.1:34813 #1 (1 connection now open)
[INFO] [03/13/2018 06:22:16.254] [routingSystem-akka.actor.default-dispatcher-3] [akka://routingSystem/user/IO-HTTP/listener-0] Bound to /0.0.0.0:8080
[INFO] [03/13/2018 06:22:16.256] [routingSystem-akka.actor.default-dispatcher-4] [akka://routingSystem/deadLetters] Message [akka.io.Tcp$Bound] from Actor[akka://routingSystem/user/IO-HTTP/listener-0#1115448017] to Actor[akka://routingSystem/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by vfarcic** [comment]
Are you using this repo as a material from "The DevOps 2.0 Toolkit" book? If you are, the following note is right below that command.

> A couple of readers commented that on rare occasions, the tests fail (probably due to concurrency). Also, NPM tends to get broken fairly often recently. To avoid problems, tests have been, temporarily, disabled. Instead the expected result you'll see a message "NPM is broken (again) so front-end tests are temporarily disabled."

In any case, if the command didn't fail, it should be OK. Those are only INFO level messages.

**Comment by junaid-ali** [comment]
My apologies, I missed the note somehow. BTW, instead of creating a Vagrant VM, I am using an AWS instance. Closing the ticket.

**Comment by p4n0p71c0n** [comment]
Just wanted you to know guys this note was only partially complete in my version of the book :( There was no mention of NPM and this being the cause......

**Comment by vfarcic** [comment]
@p4n0p71c0n which edition of the book you have and where did you get it? I'm asking that because some editions are updated instantly, while others never get updated due to restrictions of the vendor.

A while ago, *The DevOps 2.0 Toolkit* was removed from sales in vendors I control. It is now too old and much of the tech is deprecated.

**Comment by p4n0p71c0n** [comment]
@vfarcic I am reading the first printing of the Packt edition. I prefer dead tree format as I still feel it's kinder on my eyes. Obtained a few days prior from Amazon UK.

My feeling was that starting from the beginning will help explain the end, but I know the world has moved on since you wrote it :) I'll make sure to check frequently as I move through all your books...I'm enjoying them alot.
