### ISSUE TITLE
ansible-playbook swarm.yml JQ is present TASK Error

### ISSUE THREAD

**Issue by erezstmn** [vfarcic/books-ms#54]
Dear Viktor,

I am reading through your book (The Dev Ops 2.0...) and getting this error while trying to run: 
`ansible-playbook /vagrant/ansible/swarm.yml -i /vagrant/ansible/hosts/prod`

Any ideas on how to solve it?

 ## The Error:

`vagrant@cd:~$ ansible-playbook /vagrant/ansible/swarm.yml -i /vagrant/ansible/hosts/prod
 [WARNING]: Found variable using reserved name: hosts

PLAY [swarm] *****************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [10.100.192.200]

TASK [common : JQ is present] ************************************************************************************************************************
fatal: [10.100.192.200]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "W: Can't drop privileges for downloading as file '/var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)\nE: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/db86a469f5bd9bfcf02edbb73cfbacd4abcec6393e8cb33fc7aeba17548ac7a1  Hash Sum mismatch\nE: Some index files failed to download. They have been ignored, or old ones used instead.", "rc": 100, "stderr": "W: Can't drop privileges for downloading as file '/var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)\nE: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/db86a469f5bd9bfcf02edbb73cfbacd4abcec6393e8cb33fc7aeba17548ac7a1  Hash Sum mismatch\nE: Some index files failed to download. They have been ignored, or old ones used instead.\n", "stderr_lines": ["W: Can't drop privileges for downloading as file '/var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)", "E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/db86a469f5bd9bfcf02edbb73cfbacd4abcec6393e8cb33fc7aeba17548ac7a1  Hash Sum mismatch", "E: Some index files failed to download. They have been ignored, or old ones used instead."], "stdout": "Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]\nHit:2 http://archive.ubuntu.com/ubuntu xenial InRelease\nGet:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]\nGet:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]\nGet:5 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [306 kB]\nGet:6 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [2524 B]\nGet:7 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [203 kB]\nGet:8 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [8404 B]\nGet:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [783 kB]\nGet:10 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [631 kB]\nErr:10 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages\n  Hash Sum mismatch\nGet:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [253 kB]\nGet:12 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.4 kB]\nGet:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8344 B]\nFetched 981 kB in 5s (186 kB/s)\nReading package lists...\n", "stdout_lines": ["Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]", "Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease", "Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]", "Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]", "Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [306 kB]", "Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [2524 B]", "Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [203 kB]", "Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [8404 B]", "Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [783 kB]", "Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [631 kB]", "Err:10 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages", "  Hash Sum mismatch", "Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [253 kB]", "Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.4 kB]", "Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8344 B]", "Fetched 981 kB in 5s (186 kB/s)", "Reading package lists..."]}
	to retry, use: --limit @/vagrant/ansible/swarm.retry

PLAY RECAP *******************************************************************************************************************************************
10.100.192.200             : ok=1    changed=0    unreachable=0    failed=1 
`

**Comment by vfarcic** [comment]
I'm travelling today and tomorrow and probably won't have an opportunity to check it out until Wednesday. Judging by what you described, it might be the same problem as https://github.com/vfarcic/ms-lifecycle/issues/36.

Can you please pull the latest version of the ms-lifecycle repo (e.g., `git pull`, update Vagrant boxes (e.g., `vagrant box update`), and try again. If that doesn't fix the issue, I'll go through it in more detail ASAP.

**Comment by erezstmn** [comment]
I read through that issue and I also thought it might solve it but it didn't. I also pulled the latest repo with no help.

I will try to update the vagrant box and will let you know about the outcome.

All the best :)

**Comment by erezstmn** [comment]
Hi Viktor. Updating the boxes worked for me. Thanks for the help!
