### ISSUE TITLE
can't read /var/mail/debian:jessie

### ISSUE THREAD

**Issue by AJVA2580** [vfarcic/books-ms#58]
 ~/books-ms 
 ↵ 127  FROM debian:jessie
MAINTAINER Viktor Farcic "viktor@farcic.com"
RUN apt-get update && \
apt-get install -y --force-yes --no-install-recommends openjdk-7-
jdk && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*
ENV DB_DBNAME books
ENV DB_COLLECTION books
COPY run.sh /run.sh
RUN chmod +x /run.sh
COPY target/scala-2.10/books-ms-assembly-1.0.jar /bs.jar
COPY client/components /client/components
CMD ["/run.sh"]
EXPOSE 8080
FROM: can't read /var/mail/debian:jessie
zsh: command not found: MAINTAINER
zsh: command not found: RUN
zsh: command not found: jdk
ENV: DB_DBNAME: No such file or directory
ENV: DB_COLLECTION: No such file or directory
zsh: command not found: COPY
zsh: command not found: RUN
zsh: command not found: COPY
zsh: command not found: COPY
zsh: no matches found: [/run.sh]
zsh: command not found: EXPOSE

I also tried this one

 ~/books-ms 
 ↵ 127  FROM openjdk
MAINTAINER Viktor Farcic "viktor@farcic.com"

ENV DB_DBNAME books
ENV DB_COLLECTION books
ENV DB_HOST localhost

COPY run.sh /run.sh
RUN chmod +x /run.sh

COPY target/scala-2.10/books-ms-assembly-1.0.jar /bs.jar
COPY client/components /client/components

CMD ["/run.sh"]

EXPOSE 8080
FROM: can't read /var/mail/openjdk
zsh: command not found: MAINTAINER
ENV: DB_DBNAME: No such file or directory
ENV: DB_COLLECTION: No such file or directory
ENV: DB_HOST: No such file or directory
zsh: command not found: COPY
zsh: command not found: RUN
zsh: command not found: COPY
zsh: command not found: COPY
zsh: no matches found: [/run.sh]
zsh: command not found: EXPOSE

**Comment by vfarcic** [comment]
Are you trying to run all those as commands? If you are, that's the issue. Those lines are the contents of `Dockerfile` and are listed there for you to see how to construct it. Later on, you'll build a Docker image using `Dockerfile` with the `docker build` command.

As a side note, much of that book is now deprecated. I removed it from sales in channels I control (Amazon and LeanPub). The other books in the series are up-to-date, but not that one. The tech is too old.

**Comment by AJVA2580** [comment]
Hello, 

I bought the book from Amazon recently because was recommended. 

**Later on, you'll build a Docker image using Dockerfile with the docker build command.**  
Thank you for clarifying. 

Will this book teach me something about the whole project infrastructure or not? 

please advise and thank you again for your help

**Comment by vfarcic** [comment]
The book will teach you a lot. The problem is rather that it is old and hence uses old technology to solve problems that are much easier to deal with using newer tech.

**Comment by AJVA2580** [comment]
I see. 

What is the new edition that you recommend? 

Thank you again for your help.

**Comment by vfarcic** [comment]
That depends on what you're looking for. The DevOps 2.1 and 2.2 Toolkit are dedicated to Docker Swarm. The DevOps 2.3 Toolkit provides Kubernetes fundamentals. 2.4 is about using Jenkins in Kubernetes, 2.5 about self-healing and auto-scaling applications and Kubernetes clusters, and 2.6 is dedicated to Jenkins X.

P.S. Those are not different editions but different books.
