### ISSUE TITLE
Unable to find image '10.100.198.200:5000/books-ms:latest' locally

### ISSUE THREAD

**Issue by tiaa-gramajo** [vfarcic/books-ms#59]
Hi - Having issues with this command:

vagrant@cd:~/books-ms$ docker run -d --name books-ms -p 8080:8080 --link books-db:db 10.100.198.200:5000/books-ms:latest
Unable to find image '10.100.198.200:5000/books-ms:latest' locally
Pulling repository 10.100.198.200:5000/books-ms
docker: Error: image books-ms:latest not found.
See 'docker run --help'.

I see the image:
vagrant@cd:~/books-ms$ docker image ls
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
10.100.198.200:5000/book-ms          latest              ab8d8118456c        5 hours ago         510MB
10.100.198.200:5000/books-ms-tests   latest              06d2d967baa8        14 hours ago        2.33GB
mongo                                latest              f7adfc4dbcf5        9 days ago          413MB
portainer/portainer                  latest              2b4ddf654e1c        13 days ago         77.7MB
openjdk                              latest              ad1c6207e3ad        3 weeks ago         470MB
debian                               jessie              652b7a59e393        4 weeks ago         129MB
registry                             2                   f32a97de94e1        5 months ago        25.8MB

And I see the registry:
vagrant@cd:~/books-ms$ docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                    NAMES
2d725864b968        mongo                 "docker-entrypoint..."   2 hours ago         Up 2 hours          27017/tcp                books-db
fbd356de6935        registry:2            "/entrypoint.sh se..."   15 hours ago        Up 15 hours         0.0.0.0:5001->5000/tcp   registry-mirror
be7d3d73a4d5        registry:2            "/entrypoint.sh /e..."   15 hours ago        Up 15 hours         0.0.0.0:5000->5000/tcp   registry
51ce0e454ea8        portainer/portainer   "/portainer --no-a..."   15 hours ago        Up 15 hours         0.0.0.0:9000->9000/tcp   portainer

**Comment by vfarcic** [comment]
Can you please let me know where is that command used? Is it from "The DevOps 2.0 Toolkit" book, one of the articles, or somewhere else?
