### ISSUE TITLE
502  Server Hangup

### ISSUE THREAD

**Issue by chaintng** [vfarcic/books-ms#6]
When i run
`docker build -t 10.100.198.200:5000/books-ms .`

It result in error

```
Get:107 http://security.debian.org/ jessie/updates/main openjdk-7-jdk amd64 7u101-2.6.6-1~deb8u1 [16.1 MB]
Fetched 82.0 MB in 1min 4s (1281 kB/s)
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/a/avahi/libavahi-common-data_0.6.31-5_amd64.deb  502  Server Hangup [IP: 5.153.231.35 80]

E: Aborting install.
```

**Comment by vfarcic** [comment]
There is something wrong with those packages. Unfortunately, I don't control them so I can't fix the packages required for that image. Instead, I created a new image (this time using JDK Alpine as base). Please pull the latest code and let me know if everything works as expected.

**Comment by vfarcic** [comment]
Using Alpine as the base image does not work. Reverted to standard "java" base image.
