### ISSUE TITLE
Message [akka.io.Tcp$Bound] from Actor[akka://routingSystem/user/IO-HTTP/listener-0#1594456900] to Actor[akka://routingSystem/deadLetters] was not delivered.

### ISSUE THREAD

**Issue by rjfisher123** [vfarcic/books-ms#8]
Hello,

I am using the DevOps 2.0 book, when I get to Sudo Docker Run -it --rm...  on books-ms-tests I get the subject error. 

It appears that 'routingSystem/user/IO-HTTP/listener' may have ended earlier.

Any help is appreciated.

Thanks

**Comment by vfarcic** [comment]
Hi,

That log entry is only a warning from Akka. In itself, it should not be an issue. Did you experience any problem with the commands that follow?

**Comment by rjfisher123** [comment]
No, I kept playing with it and then I saw the tests running. Thanks for responding.

**Comment by tobyforever** [comment]
the console seems to hang indefinitely after this.anything wrong?  the console output is as follows:

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo docker run -it --rm -v $PWD/client/components:/source/client/components -v $PWD/client/test:/source/client/test -v $PWD/src:/source/src -v $PWD/target:/source/target -p 8080:8080 --env TEST_TYPE=watch-front vfarcic/books-ms-tests
>>> NPM is broken (again) so front-end tests are temporarily disabled.
mongod --help for help and startup options
Wed Oct 12 07:58:14.849 [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data/db/ 64-bit host=4750e8c64bb1
Wed Oct 12 07:58:14.854 [initandlisten] db version v2.4.10
Wed Oct 12 07:58:14.858 [initandlisten] git version: nogitversion
Wed Oct 12 07:58:14.860 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
Wed Oct 12 07:58:14.862 [initandlisten] allocator: tcmalloc
Wed Oct 12 07:58:14.862 [initandlisten] options: {}
Wed Oct 12 07:58:14.870 [initandlisten] journal dir=/data/db/journal
Wed Oct 12 07:58:14.872 [initandlisten] recover : no journal files present, no recovery needed
Wed Oct 12 07:58:14.977 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
Wed Oct 12 07:58:14.978 [FileAllocator] creating directory /data/db/_tmp
Wed Oct 12 07:58:14.982 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0.002 secs
Wed Oct 12 07:58:14.994 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
Wed Oct 12 07:58:14.997 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.001 secs
Wed Oct 12 07:58:15.002 [initandlisten] waiting for connections on port 27017
Wed Oct 12 07:58:15.005 [websvr] admin web console waiting for connections on port 28017
[info] Loading project definition from /source/project
[info] Set current project to books-ms (in build file:/source/)
[info] Compiling 2 Scala sources to /source/target/scala-2.10/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[info]   Compilation completed in 27.358 s
[info] Running com.technologyconversations.api.Service
07:59:42.118 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Registering Scala Conversions.
07:59:42.128 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Deserializers for Scala Conversions registering
07:59:42.129 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Serializers for Scala Conversions registering
07:59:42.131 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up OptionSerializer
07:59:42.136 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaProductSerializer
07:59:42.137 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaCollectionSerializer
07:59:42.140 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaRegexSerializers
07:59:42.143 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Hooking up scala.util.matching.Regex serializer
07:59:42.145 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Reached base registration method on MongoConversionHelper.
Wed Oct 12 07:59:43.270 [initandlisten] connection accepted from 127.0.0.1:45127 #1 (1 connection now open)
[INFO] [10/12/2016 07:59:43.780] [routingSystem-akka.actor.default-dispatcher-3] [akka://routingSystem/user/IO-HTTP/listener-0] Bound to /0.0.0.0:8080
[INFO] [10/12/2016 07:59:43.793] [routingSystem-akka.actor.default-dispatcher-2] [akka://routingSystem/deadLetters] Message [akka.io.Tcp$Bound] from Actor[akka://routingSystem/user/IO-HTTP/listener-0#-1531932518] to Actor[akka://routingSystem/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
